project:
  type: website

website:
  title: "My Learnings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AkhilaSunesh
      - icon: x
        href: https://x.com
      - icon: instagram
        href: https://instagram.com
format:
  html:
    theme: journal
    css: styles.css



